sprint4 done
ClevertecFrontendLab/alexwerac pull request #2
Opened 2023-02-22 18:26 UTC by alexwerac

Есть вопрос по поводу отправки повторного запроса всех книг после возвращения по крошкам. Я использовал в rtk query refetchOnMountOrArgChange: true, чтобы тесты проходились, но это не выглядит как нужная вещь т. к. на странице книги данные не мутируются никак и их можно брать из кеша.

2023-02-22 18:31 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 87%.
Общее количество тестов: 16.
Количество непройденных тестов: 2.
***
**active-category-programming.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexwerac/1677090709/active-category-programming.png)
***
**bread crumbs -- tablet -- transfer from all books category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexwerac/1677090709/bread%20crumbs%20--%20tablet%20--%20transfer%20from%20all%20books%20category%20to%20book%20page%20(failed).png)
***
**bread crumbs -- tablet -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexwerac/1677090709/bread%20crumbs%20--%20tablet%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**clearing-search-input.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexwerac/1677090709/clearing-search-input.png)
***
**empty-category.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexwerac/1677090709/empty-category.png)
***
**find-books.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexwerac/1677090709/find-books.png)
***
**search-result-not-found.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexwerac/1677090709/search-result-not-found.png)

2023-02-22 18:37 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 13.
Количество непройденных тестов: 1.
***
**active-category-programming.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexwerac/1677091069/active-category-programming.png)
***
**bread crumbs -- transfer from programming category to book page -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexwerac/1677091069/bread%20crumbs%20--%20transfer%20from%20programming%20category%20to%20book%20page%20--%20before%20each%20hook%20(failed).png)
***
**clearing-search-input.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexwerac/1677091069/clearing-search-input.png)
***
**empty-category.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexwerac/1677091069/empty-category.png)
***
**find-books.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexwerac/1677091069/find-books.png)
***
**search-result-not-found.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexwerac/1677091069/search-result-not-found.png)

2023-02-23 03:21 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 93%.
Общее количество тестов: 16.
Количество непройденных тестов: 1.
***
**active-category-programming.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexwerac/1677122485/active-category-programming.png)
***
**bread crumbs -- desktop -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexwerac/1677122485/bread%20crumbs%20--%20desktop%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**clearing-search-input.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexwerac/1677122485/clearing-search-input.png)
***
**empty-category.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexwerac/1677122485/empty-category.png)
***
**find-books.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexwerac/1677122485/find-books.png)
***
**search-result-not-found.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexwerac/1677122485/search-result-not-found.png)

2023-02-23 03:23 UTC, alexwerac commented
После последнего исправления все тесты локально проходятся.

2023-02-23 06:19 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 87%.
Общее количество тестов: 16.
Количество непройденных тестов: 2.
***
**active-category-programming.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexwerac/1677133146/active-category-programming.png)
***
**bread crumbs -- desktop -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexwerac/1677133146/bread%20crumbs%20--%20desktop%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**bread crumbs -- tablet -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexwerac/1677133146/bread%20crumbs%20--%20tablet%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**clearing-search-input.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexwerac/1677133146/clearing-search-input.png)
***
**empty-category.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexwerac/1677133146/empty-category.png)
***
**find-books.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexwerac/1677133146/find-books.png)
***
**search-result-not-found.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexwerac/1677133146/search-result-not-found.png)

2023-02-23 07:40 UTC, Gaurrus requested changes

2023-02-23 07:40 UTC, Gaurrus commented on src/components/nav/nav-component.jsx
>  export const Nav = () => {
![image](https://user-images.githubusercontent.com/85307211/220844972-cdfef883-0c22-4ea6-aa6d-95fe280aabff.png)
![image](https://user-images.githubusercontent.com/85307211/220845030-dc028d4b-b4f8-4650-8f9f-49a0332545a1.png)
думаю какая-то проблема с меню категорий - не смог тест на кликнуть на "Программирование" а потом не смог кликнуть на карточку книги

2023-02-23 07:49 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 16.
Количество непройденных тестов: 0.
***
**active-category-programming.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexwerac/1677138556/active-category-programming.png)
***
**clearing-search-input.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexwerac/1677138556/clearing-search-input.png)
***
**empty-category.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexwerac/1677138556/empty-category.png)
***
**find-books.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexwerac/1677138556/find-books.png)
***
**search-result-not-found.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexwerac/1677138556/search-result-not-found.png)

2023-02-23 07:50 UTC, Gaurrus approved these changes

2023-02-23 09:11 UTC, merged